[project]
name = "myapp"
version = "1.0.0"
description = "Teste S4"
dependencies = [
    "flask",
    "flask-sqlalchemy"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"